### ISSUE TITLE
Question: How long did it take to pre-train afriberta?

### ISSUE THREAD

**Issue by RuanVisser** [keleog/afriberta#1]
I see in the paper ``Small Data? No Problem! Exploring the Viability of Pretrained Multilingual Language Models for Low-resource Languages`` the configurations and hardware (2 x V100) used to pre-train all models, however, I cannot find any details on the estimated time to pre-train the each model.
Is there any estimate on the time it would take to train such models (on similar hardware)?

**Comment by keleog** [comment]
Hi, apologies for the late reply. The estimated time was around 72 hours for AfriBERTa large. Feel free to reopen if you have any more questions.
